### ISSUE TITLE
Error on gitlab ci 

### ISSUE THREAD

**Issue by g-apparence** [CleverCloud/clever-tools-dockerhub#3]
Hi,
maybe I'm doing it wront but starting this image is not working using Gitlab

Used this : 
```yaml
deploy-staging:
  stage: deploy
  image: clevercloud/clever-tools:latest
  variables:
    APP_NAME: staging
    APP_ID: XXXXX
 script:
    - clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
    - clever link ${APP_ID}
    - clever deploy -a ${APP_NAME}
  environment:
    name: staging
    url: https://staging-server.cleverapps.io
```

Error : 
```sh
Using docker image sha256:62b45ec640ad8456d78a38176f2d151df4d8983baa016884ab7d7f80ea28a1b0 for clevercloud/clever-tools:latest with digest clevercloud/clever-tools@sha256:fba465eeafa1a91c8b20239a69dc5725478c619dbc48f70d5e559e958bbc6bf7 ...
Too many arguments: sh
Unknown option: c
Usage: clever
```

Tried without anything in the script part makes the same result, So I guess it's related directly to the docker image.
